services:
    db:
        image: postgres:16
        container_name: file_extractor_db
        env_file:
            - .flaskenv
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            interval: 5s
            timeout: 5s
            retries: 10
        ports:
            - "9898:9898"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - file_extractor_network
    web:
        build: .
        container_name: file_extractor_web
        working_dir: /app
        command: gunicorn --reload -c gunicorn.conf.py app:app
        env_file:
            - .flaskenv
        ports:
            - "9797:9797"
        volumes:
            - .:/app
        depends_on:
            db:
                condition: service_healthy
        networks:
            - file_extractor_network
volumes:
    postgres_data:
networks:
    file_extractor_network:
        driver: bridge
